[package]
name = "fspec"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
fspec-core = { path = "../fspec-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
