
[identifiers]
name = "{snake_case}"
version = "{int(3)}"

# custom validators
[validator.png_check]
cmd = "scripts/png_check {file}"
# optional extras later:
# cwd = "art/"
# timeout = 10
# severity = "error" | "warning"

[file.texture]
pattern    = "art/textures/**/{name}_{version}.png"
rules = [
  "validate png_check",
]